In [ ]:
import pandas as pd 


path = r"/home/said/Desktop/ai_2/AI_python/Pandas/students.csv"
path2 = r"/home/said/Desktop/ai_2/AI_python/Pandas/movie.csv"

df = pd.read_csv(path)
df2 = pd.read_csv(path2)

# print(df)
# print(df2.head(30))
# print(df.shape) 

In [5]:
df

Hours  Scores
0     2.5      21
1     5.1      47
2     3.2      27
3     8.5      75
4     3.5      30
5     1.5      20
6     9.2      88
7     5.5      60
8     8.3      81
9     2.7      25
10    7.7      85
11    5.9      62
12    4.5      41
13    3.3      42
14    1.1      17
15    8.9      95
16    2.5      30
17    1.9      24
18    6.1      67
19    7.4      69
20    2.7      30
21    4.8      54
22    3.8      35
23    6.9      76
24    7.8      86

In [10]:
import numpy as np 
x = np.array(df.Hours)
y = np.array(df.Scores)
n = len(x)

In [8]:
y

array([21, 47, 27, 75, 30, 20, 88, 60, 81, 25, 85, 62, 41, 42, 17, 95, 30,
       24, 67, 69, 30, 54, 35, 76, 86])

In [13]:
m = (n*np.sum(x*y)-np.sum(x)*np.sum(y))/(n*np.sum(np.power(x,2))-np.power(np.sum(x),2))
b = (np.sum(y)-m*np.sum(x))/n

In [12]:
m

9.77580339078746

In [14]:
b

2.483673405373247

In [15]:
y1 = m*x+b
e = 1/n*np.sum(np.power(y-y1,2))

In [16]:
e

28.882730509245466

In [17]:
y1

array([26.92318188, 52.3402707 , 33.76624426, 85.57800223, 36.69898527,
       17.14737849, 92.4210646 , 56.25059205, 83.62284155, 28.87834256,
       77.75735951, 60.16091341, 46.47478866, 34.74382459, 13.23705714,
       89.48832358, 26.92318188, 21.05769985, 62.11607409, 74.8246185 ,
       28.87834256, 49.40752968, 39.63172629, 69.9367168 , 78.73493985])

In [18]:
x

array([2.5, 5.1, 3.2, 8.5, 3.5, 1.5, 9.2, 5.5, 8.3, 2.7, 7.7, 5.9, 4.5,
       3.3, 1.1, 8.9, 2.5, 1.9, 6.1, 7.4, 2.7, 4.8, 3.8, 6.9, 7.8])

In [19]:
y

array([21, 47, 27, 75, 30, 20, 88, 60, 81, 25, 85, 62, 41, 42, 17, 95, 30,
       24, 67, 69, 30, 54, 35, 76, 86])